name: Build .NET Assembly
on:
  push:
    branches: [ "main" ]
    paths:
      - 'MyAssembly/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'MyAssembly/**'

jobs:
  # Assembly is cross-platform, so only needs to be built on Linux.
  build-dotnet:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup .NET 8.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Build .NET Standard 2.0 Assembly
      run: dotnet build MyAssembly/MyAssembly.csproj
    
