# This workflow will setup .NET and MATLAB on the host machine
name: Run MATLAB Interface to .NET Examples

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-examples:
    strategy:
      matrix:
        os: [ 'windows-latest', 'ubuntu-latest', 'macos-latest' ]
        dotnet-version: [ '8.0.x' ]

    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
      
    - name: Setup .NET ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Build .NET Code
      run: dotnet build MyAssembly/MyAssembly.csproj

    - name: Setup Latest MATLAB
      uses: matlab-actions/setup-matlab@v2
      with:
        release: R2025a
    
    - name: Run MATLAB Examples
      uses: matlab-actions/run-command@v2
      with:
        command: cd examples, configureDotnet, createDelegates, createGenerics, invokeGenericMethods
