name: Run MATLAB Examples

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      command:
        required: true
        type: string

jobs:
  test-matlab:
    runs-on: ${{ inputs.os }}
    steps:          
    - name: Setup Latest MATLAB
      uses: matlab-actions/setup-matlab@v2
      with:
        cache: true
        
    - name: Checkout MATLAB Code
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          .github
          examples
        
    - name: Run MATLAB Code
      uses: matlab-actions/run-command@v2
      with:
        command: ${{ inputs.command }}
